"use strict";

const constants = {
  environment: {
    LOCAL: "local",
    DEVELOPMENT: "development",
    TEST: "test",
    PRODUCTION: "production",
  },
  http: {
    status: {
      OK: 200,
      CREATED: 201,
      ACCEPTED: 202,
      NOCONTENT: 204,
      MULTI_STATUS: 207,
      REDIRECT: 301,
      BAD_REQUEST: 400,
      UNAUTHORIZED: 401,
      FORBIDDEN: 403,
      CONFLICT: 409,
      INTERNAL_SERVER_ERROR: 500,
      NOT_FOUND: 404,
    },
  },
  error: {
    validation: {},
    message: {
      // HTTP Status code messages
      HTTP_STATUS_CODE_201: "Created",
      HTTP_STATUS_CODE_400: "Bad Request.",
      HTTP_STATUS_CODE_301: "Redirect to other url",
      HTTP_STATUS_CODE_401: "Unauthorized.",
      HTTP_STATUS_CODE_403: "Forbidden.",
      HTTP_STATUS_CODE_404: "The specified resource was not found.",
      HTTP_STATUS_CODE_409: "Resource already exists",
      HTTP_STATUS_CODE_500: "Internal Server Error.",
      INVALID_LOGIN: "Invalid Login",
      EMAIL_MISSING: "Email Missing",
      PAYMENT_ACCOUNT_ID_MISSING: "Payment Account Id Missing",
      INVALID_PAYMENT_ACCOUNT_ID: "Invalid Payment Account Id provided",
    },
  },
  models: {
    USER_TABLE: "users",
    BANNER_TABLE: "banners",
    DOCTOR_TABLE: "doctors",
    CLINIC_TABLE: "clinics",
    CLINIC_PATIENT_TABLE: "clinic_patient_mappings",
    DOCTOR_PATIENT_TABLE: "doctor_patient_mappings",
    PATIENT_TABLE: "patients",
    PROCEDURE_TABLE: "procedures",
    SERVICE_TABLE: "services",
    SLOT_TABLE: "slots",
    BLOCKED_SLOT_TABLE: "blocked_slots",
    APPOINTMENT_TABLE: "appointments",
    TREATMENT_TABLE: "treatments",
    TREATMENT_PRESCRIPTION_TABLE: "treatment_prescriptions",
    TREATMENT_PLAN_TABLE: "treatment_plans",
    TREATMENT_HISTORY_TABLE: "treatment_histories",
    DOCTOR_SERVICE_MAP_TABLE: "doctor_service_mappings",
    BOOKING_TABLE: "bookings",
    DENTAL_CHART_TABLE: "dental_charts",
    DENTAL_NOTE_TABLE: "dental_notes",
    NOTE_TABLE: "notes",
    XRAY_TABLE: "xrays",
    INVESTIGATION_TABLE: "investigations",
    PAYMENT_TABLE: "treatment_payments",
    STAFF_TABLE: "staffs",
    CLINIC_STAFF_TABLE: "clinic_staff_mappings",
    COMPREHENSIVE_EXAMINATION_TABLE: "comprehensive_examinations",
    DOCUMENT_TABLE: "documents",
  },
  bcrypt: {
    SALT_ROUNDS: 10,
  },
  time: {
    TOKEN_EXPIRES_IN: 1000 * 60 * 60 * 24 * 30,
    REFRESH_TOKEN_EXPIRES_IN: "20d",
  },
  mime: {
    imageMime: ["jpeg", "jpg", "png", "gif", "webp"],
    videoMime: ["mp4", "mpeg", "ogg", "webm", "m4v", "mov", "mkv"],
    docsMime: [
      "pdf",
      "ppt",
      "pptx",
      "docx",
      "application/msword",
      "msword",
      "vnd.openxmlformats-officedocument.wordprocessingml.document",
    ],
  },
  static: {
    slotInterval: 10,
  },
  toothColors: ["#0000FF", "#000000", "#FF0000", "#FFFF00"],
};

export default constants;
